#!/usr/bin/env python
# encoding: utf-8

MM_TYPES = {
    'Amber': {
        'H': {'element': 'H'},
        'HO': {'element': 'H'},
        'HS': {'element': 'H'},
        'HC': {'element': 'H'},
        'H1': {'element': 'H'},
        'H2': {'element': 'H'},
        'H3': {'element': 'H'},
        'HP': {'element': 'H'},
        'HA': {'element': 'H'},
        'H4': {'element': 'H'},
        'H5': {'element': 'H'},
        'HW': {'element': 'H'},
        'O': {'element': 'O'},
        'O2': {'element': 'O'},
        'OW': {'element': 'O'},
        'OH': {'element': 'O'},
        'OS': {'element': 'O'},
        'CT': {'element': 'C'},
        'CA': {'element': 'C'},
        'CM': {'element': 'C'},
        'C': {'element': 'C'},
        'C*': {'element': 'C'},
        'CB': {'element': 'C'},
        'CC': {'element': 'C'},
        'CN': {'element': 'C'},
        'CK': {'element': 'C'},
        'CQ': {'element': 'C'},
        'CW': {'element': 'C'},
        'CV': {'element': 'C'},
        'CR': {'element': 'C'},
        'CY': {'element': 'C'},
        'CD': {'element': 'C'},
        'N': {'element': 'N'},
        'NA': {'element': 'N'},
        'N2': {'element': 'N'},
        'N*': {'element': 'N'},
        'NC': {'element': 'N'},
        'NB': {'element': 'N'},
        'N3': {'element': 'N'},
        'NP': {'element': 'N'},
        'NO': {'element': 'N'},
        'S': {'element': 'S'},
        'SH': {'element': 'S'},
        'P': {'element': 'P'},
        'IM': {'element': 'Cl'},
        'LI': {'element': 'Li'},
        'IP': {'element': 'Na'},
        'K': {'element': 'K'},
        'RB': {'element': 'Rb'},
        'CS': {'element': 'Cs'},
        'I': {'element': 'I'},
        'F': {'element': 'F'},
        'IB': {'element': 'Na'},
    },
    'Amber99SB': {
        'H':  {'link_atom': 'Test', 'element': 'H', 'MM3PRO': ['20', '19', '22', '23', '24', '25']},
        'HO': {'link_atom': 'Test', 'element': 'H', 'MM3PRO': ['26']},
        'HS': {'link_atom': 'Test', 'element': 'H', 'MM3PRO': ['27']},
        'H1': {'link_atom': 'Test', 'element': 'H', 'MM3PRO': ['19']},
        'H2': {'link_atom': 'Test', 'element': 'H', 'MM3PRO': ['']},         #Only used for ADN (not ADN in MM3PRO)
        'H3': {'link_atom': 'Test', 'element': 'H', 'MM3PRO': ['']},         #Not used in standard residues nor ADN
        'H4': {'link_atom': 'Test', 'element': 'H', 'MM3PRO': ['19']},
        'H5': {'link_atom': 'Test', 'element': 'H', 'MM3PRO': ['19']},
        'HW': {'link_atom': 'Test', 'element': 'H', 'MM3PRO': ['26']},
        'HC': {'link_atom': 'Test', 'element': 'H', 'MM3PRO': ['19']},
        'HA': {'link_atom': 'Test', 'element': 'H', 'MM3PRO': ['19']},
        'HP': {'link_atom': 'Test', 'element': 'H', 'MM3PRO': ['19']},
        'OH': {'link_atom': 'Test', 'element': 'O', 'MM3PRO': ['17']},
        'OS': {'link_atom': 'Test', 'element': 'O', 'MM3PRO': ['']},         #Only used for ADN (not ADN in MM3PRO)
        'O':  {'link_atom': 'Test', 'element': 'O', 'MM3PRO': ['13']},
        'O2': {'link_atom': 'Test', 'element': 'O', 'MM3PRO': ['14']},
        'OW': {'link_atom': 'Test', 'element': 'O', 'MM3PRO': ['17']},
        'CT': {'link_atom': 'Test', 'element': 'C', 'MM3PRO': ['1']},
        'CH': {'link_atom': 'Test', 'element': 'C', 'MM3PRO': ['']},         #Not used in standard residues nor ADN
        'C2': {'link_atom': 'Test', 'element': 'C', 'MM3PRO': ['']},         #Not used in standard residues nor ADN
        'C3': {'link_atom': 'Test', 'element': 'C', 'MM3PRO': ['']},         #Not used in standard residues nor ADN
        'C':  {'link_atom': 'Test', 'element': 'C', 'MM3PRO': ['2', '3']},
        'C*': {'link_atom': 'Test', 'element': 'C', 'MM3PRO': ['6']},
        'CA': {'link_atom': 'Test', 'element': 'C', 'MM3PRO': ['4', '5']},
        'CB': {'link_atom': 'Test', 'element': 'C', 'MM3PRO': ['4']},
        'CC': {'link_atom': 'Test', 'element': 'C', 'MM3PRO': ['6']},
        'CN': {'link_atom': 'Test', 'element': 'C', 'MM3PRO': ['4']},
        'CM': {'link_atom': 'Test', 'element': 'C', 'MM3PRO': ['']},         #Only used for ADN (not ADN in MM3PRO)
        'CK': {'link_atom': 'Test', 'element': 'C', 'MM3PRO': ['']},         #Only used for ADN (not ADN in MM3PRO)
        'CQ': {'link_atom': 'Test', 'element': 'C', 'MM3PRO': ['']},         #Only used for ADN (not ADN in MM3PRO)
        'CD': {'link_atom': 'Test', 'element': 'C', 'MM3PRO': ['']},         #Not used in standard residues nor ADN
        'CE': {'link_atom': 'Test', 'element': 'C', 'MM3PRO': ['']},         #Not used in standard residues nor ADN
        'CF': {'link_atom': 'Test', 'element': 'C', 'MM3PRO': ['']},         #Not used in standard residues nor ADN
        'CP': {'link_atom': 'Test', 'element': 'C', 'MM3PRO': ['']},         #Not used in standard residues nor ADN
        'CI': {'link_atom': 'Test', 'element': 'C', 'MM3PRO': ['']},         #Not used in standard residues nor ADN
        'CJ': {'link_atom': 'Test', 'element': 'C', 'MM3PRO': ['']},         #Not used in standard residues nor ADN
        'CW': {'link_atom': 'Test', 'element': 'C', 'MM3PRO': ['6']},        
        'CV': {'link_atom': 'Test', 'element': 'C', 'MM3PRO': ['6']},        #We assign this type in non-protonated Histidine
        'CR': {'link_atom': 'Test', 'element': 'C', 'MM3PRO': ['7']},
        'CY': {'link_atom': 'Test', 'element': 'C', 'MM3PRO': ['']},         #Not used in standard residues nor ADN
        'C0': {'link_atom': 'Test', 'element': 'Ca', 'MM3PRO': ['']},        #Not used in standard residues nor ADN
        'MG': {'link_atom': 'Test', 'element': 'Mg', 'MM3PRO': ['']},        #Not used in standard residues nor ADN
        'N':  {'link_atom': 'Test', 'element': 'N', 'MM3PRO': ['8']},
        'NA': {'link_atom': 'Test', 'element': 'N', 'MM3PRO': ['12', '11']},
        'N2': {'link_atom': 'Test', 'element': 'N', 'MM3PRO': ['10']},
        'N*': {'link_atom': 'Test', 'element': 'N', 'MM3PRO': ['']},         #Only used for ADN (not ADN in MM3PRO)
        'NP': {'link_atom': 'Test', 'element': 'N', 'MM3PRO': ['']},         #Not used in standard residues nor ADN
        'NQ': {'link_atom': 'Test', 'element': 'N', 'MM3PRO': ['']},         #Not used in standard residues nor ADN
        'NB': {'link_atom': 'Test', 'element': 'N', 'MM3PRO': ['11']},       #We assign this type in non-protonated Histidine Nitrogens
        'NC': {'link_atom': 'Test', 'element': 'N', 'MM3PRO': ['']},         #Only used for ADN (not ADN in MM3PRO)
        'NT': {'link_atom': 'Test', 'element': 'N', 'MM3PRO': ['']},         #Not used in standard residues nor ADN
        'N3': {'link_atom': 'Test', 'element': 'N', 'MM3PRO': ['9']},
        'S':  {'link_atom': 'Test', 'element': 'S', 'MM3PRO': ['18']},
        'SH': {'link_atom': 'Test', 'element': 'S', 'MM3PRO': ['18']},
        'P':  {'link_atom': 'Test', 'element': 'P', 'MM3PRO': ['']},          #Only used for ADN (not ADN in MM3PRO)
        'LP': {'link_atom': 'Test', 'element': '', 'MM3PRO': ['']},          #Not used in standard residues nor ADN
        'F':  {'link_atom': 'Test', 'element': 'F', 'MM3PRO': ['']},          #Not used in standard residues nor ADN
        'CL': {'link_atom': 'Test', 'element': 'Cl', 'MM3PRO': ['']},        #Not used in standard residues nor ADN
        'BR': {'link_atom': 'Test', 'element': 'Br', 'MM3PRO': ['']},        #Not used in standard residues nor ADN
        'I':  {'link_atom': 'Test', 'element': 'I', 'MM3PRO': ['']},          #Not used in standard residues nor ADN
        'FE': {'link_atom': 'Test', 'element': 'Fe', 'MM3PRO': ['']},        #Not used in standard residues nor ADN
        'EP': {'link_atom': 'Test', 'element': '', 'MM3PRO': ['']},          #Not used in standard residues nor ADN
        'OG': {'link_atom': 'Test', 'element': 'O', 'MM3PRO': ['']},         #Not used in standard residues nor ADN    
        'OL': {'link_atom': 'Test', 'element': 'O', 'MM3PRO': ['']},         #Not used in standard residues nor ADN
        'AC': {'link_atom': 'Test', 'element': 'C', 'MM3PRO': ['']},         #Not used in standard residues nor ADN    
        'EC': {'link_atom': 'Test', 'element': 'C', 'MM3PRO': ['']},         #Not used in standard residues nor ADN
    },
    'GAFF': {
        'C': {'element': 'C', 'MM3': ['3', '2']},
        'C1': {'element': 'C', 'MM3': ['4']},
        'C2': {'element': 'C', 'MM3': ['2', '38', '57']},
        'C3': {'element': 'C', 'MM3': ['1', '22', '56']},
        'CA': {'element': 'C', 'MM3': ['2']},
        'CP': {'element': 'C', 'MM3': ['2']},
        'CQ': {'element': 'C', 'MM3': ['2']},
        'CC': {'element': 'C', 'MM3': ['2']},
        'CD': {'element': 'C', 'MM3': ['2']},
        'CE': {'element': 'C', 'MM3': ['2']},
        'CF': {'element': 'C', 'MM3': ['2']},
        'CG': {'element': 'C', 'MM3': ['4']},
        'CH': {'element': 'C', 'MM3': ['4']},
        'CX': {'element': 'C', 'MM3': ['22']},
        'CY': {'element': 'C', 'MM3': ['56']},
        'CU': {'element': 'C', 'MM3': ['38']},
        'CV': {'element': 'C', 'MM3': ['57']},
        'CZ': {'element': 'C', 'MM3': ['2']},
        'H1': {'element': 'H', 'MM3': ['5']},
        'H2': {'element': 'H', 'MM3': ['5']},
        'H3': {'element': 'H', 'MM3': ['5']},
        'H4': {'element': 'H', 'MM3': ['5']},
        'H5': {'element': 'H', 'MM3': ['5']},
        'HA': {'element': 'H', 'MM3': ['5']},
        'HC': {'element': 'H', 'MM3': ['5', '124']},
        'HN': {'element': 'H', 'MM3': ['23', '28', '48']},
        'HO': {'element': 'H', 'MM3': ['21', '73']},
        'HP': {'element': 'H', 'MM3': ['5']},
        'HS': {'element': 'H', 'MM3': ['44']},
        'HW': {'element': 'H', 'MM3': ['21']},
        'HX': {'element': 'H', 'MM3': ['5']},
        'F': {'element': 'F', 'MM3': ['11']},
        'CL': {'element': 'Cl', 'MM3': ['12']},
        'BR': {'element': 'Br', 'MM3': ['13']},
        'I': {'element': 'I', 'MM3': ['14']},
        'N': {'element': 'N', 'MM3': ['9']},
        'N1': {'element': 'N', 'MM3': ['10']},
        'N2': {'element': 'N', 'MM3': ['37']},
        'N3': {'element': 'N', 'MM3': ['8']},
        'N4': {'element': 'N', 'MM3': ['39']},
        'NA': {'element': 'N', 'MM3': ['8', '40']},
        'NB': {'element': 'N', 'MM3': ['8']},
        'NC': {'element': 'N', 'MM3': ['37']},
        'ND': {'element': 'N', 'MM3': ['37']},
        'NE': {'element': 'N', 'MM3': ['37']},
        'NF': {'element': 'N', 'MM3': ['37']},
        'NH': {'element': 'N', 'MM3': ['8']},
        'NO': {'element': 'N', 'MM3': ['46']},
        'O': {'element': 'O', 'MM3': ['7']},
        'OH': {'element': 'O', 'MM3': ['6']},
        'OS': {'element': 'O', 'MM3': ['6', '41']},
        'OW': {'element': 'O', 'MM3': ['6']},
        'P2': {'element': 'P', 'MM3': ['60']},
        'P3': {'element': 'P', 'MM3': ['25']},
        'P4': {'element': 'P', 'MM3': ['25']},
        'P5': {'element': 'P', 'MM3': ['60']},
        'PB': {'element': 'P', 'MM3': ['60']},
        'PC': {'element': 'P', 'MM3': ['60']},
        'PD': {'element': 'P', 'MM3': ['60']},
        'PE': {'element': 'P', 'MM3': ['60']},
        'PF': {'element': 'P', 'MM3': ['60']},
        'PX': {'element': 'P', 'MM3': ['60']},
        'PY': {'element': 'P', 'MM3': ['60']},
        'S': {'element': 'S', 'MM3': ['42']},
        'S2': {'element': 'S', 'MM3': ['15']},
        'S4': {'element': 'S', 'MM3': ['15', '17']},
        'S6': {'element': 'S', 'MM3': ['18']},
        'SH': {'element': 'S', 'MM3': ['15']},
        'SS': {'element': 'S', 'MM3': ['15', '42', '104']},
        'SX': {'element': 'S', 'MM3': ['17']},
        'SY': {'element': 'S', 'MM3': ['18']}
    },
    'Dreiding': {
        'H_': {'element': 'H'},
        'H_B': {'element': 'H'},
        'H_HB': {'element': 'H'},
        'B_2': {'element': 'B'},
        'B_3': {'element': 'B'},
        'C_3': {'element': 'C'},
        'C_R': {'element': 'C'},
        'C_2': {'element': 'C'},
        'C_1': {'element': 'C'},
        'N_3': {'element': 'N'},
        'N_R': {'element': 'N'},
        'N_2': {'element': 'N'},
        'N_1': {'element': 'N'},
        'O_3': {'element': 'O'},
        'O_R': {'element': 'O'},
        'O_2': {'element': 'O'},
        'O_1': {'element': 'O'},
        'F_': {'element': 'F'},
        'AL3': {'element': 'Al'},
        'SI3': {'element': 'Si'},
        'P_3': {'element': 'P'},
        'S_3': {'element': 'S'},
        'CL': {'element': 'Cl'},
        'GA3': {'element': 'Ga'},
        'GE3': {'element': 'Ge'},
        'AS3': {'element': 'As'},
        'SE3': {'element': 'Se'},
        'BR': {'element': 'Br'},
        'IN3': {'element': 'In'},
        'SN3': {'element': 'Sn'},
        'SB3': {'element': 'Sb'},
        'TE3': {'element': 'Te'},
        'I_': {'element': 'I'},
        'NA': {'element': 'Na'},
        'CA': {'element': 'Ca'},
        'FE': {'element': 'Fe'},
        'FN': {'element': 'Fe'}
    },
    'UFF': {
        'C_3': {'element': 'C', 'MM3': ['1']},
        'C_22': {'element': 'C', 'MM3': ['22']},
        'C_56': {'element': 'C', 'MM3': ['56']},
        'C_2': {'element': 'C', 'MM3': ['2']},
        'C_3C': {'element': 'C', 'MM3': ['3']},
        'C_29': {'element': 'C', 'MM3': ['29']},
        'C_30': {'element': 'C', 'MM3': ['30']},
        'C_38': {'element': 'C', 'MM3': ['38']},
        'C_57': {'element': 'C', 'MM3': ['57']},
        'C_113': {'element': 'C', 'MM3': ['113']},
        'C_114': {'element': 'C', 'MM3': ['114']},
        'C_R': {'element': 'C', 'MM3': ['2']},
        'C_50': {'element': 'C', 'MM3': ['50']},
        'C_58': {'element': 'C', 'MM3': ['58']},
        'C_67': {'element': 'C', 'MM3': ['67']},
        'C_71': {'element': 'C', 'MM3': ['71']},
        'C_1': {'element': 'C', 'MM3': ['4']},
        'C_68': {'element': 'C', 'MM3': ['68']},
        'C_106': {'element': 'C', 'MM3': ['106']},
        'H_': {'element': 'H', 'MM3': ['5']},
        'H_21': {'element': 'H', 'MM3': ['21']},
        'H_23': {'element': 'H', 'MM3': ['23']},
        'H_24': {'element': 'H', 'MM3': ['24']},
        'H_28': {'element': 'H', 'MM3': ['28']},
        'H_36': {'element': 'H', 'MM3': ['36']},
        'H_44': {'element': 'H', 'MM3': ['44']},
        'H_48': {'element': 'H', 'MM3': ['48']},
        'H_73': {'element': 'H', 'MM3': ['73']},
        'H_124': {'element': 'H', 'MM3': ['124']},
        'H_B': {'element': 'H', 'MM3': ['5']},
        'O_3': {'element': 'O', 'MM3': ['6']},
        'O_49': {'element': 'O', 'MM3': ['49']},
        'O_69': {'element': 'O', 'MM3': ['69']},
        'O_70': {'element': 'O', 'MM3': ['70']},
        'O_75': {'element': 'O', 'MM3': ['75']},
        'O_145': {'element': 'O', 'MM3': ['145']},
        'O_3_Z': {'element': 'O', 'MM3': ['6']},
        'O_R': {'element': 'O', 'MM3': ['6']},
        'O_41': {'element': 'O', 'MM3': ['41']},
        'O_47': {'element': 'O', 'MM3': ['47']},
        'O_77': {'element': 'O', 'MM3': ['77']},
        'O_78': {'element': 'O', 'MM3': ['78']},
        'O_79': {'element': 'O', 'MM3': ['79']},
        'O_80': {'element': 'O', 'MM3': ['80']},
        'O_81': {'element': 'O', 'MM3': ['81']},
        'O_82': {'element': 'O', 'MM3': ['82']},
        'O_148': {'element': 'O', 'MM3': ['148']},
        'O_149': {'element': 'O', 'MM3': ['149']},
        'O_2': {'element': 'O', 'MM3': ['7']},
        'O_159': {'element': 'O', 'MM3': ['159']},
        'O_1': {'element': 'O', 'MM3': ['7']},
        'N_3': {'element': 'N', 'MM3': ['8']},
        'N_39': {'element': 'N', 'MM3': ['39']},
        'N_146': {'element': 'N', 'MM3': ['146']},
        'N_150': {'element': 'N', 'MM3': ['150']},
        'N_155': {'element': 'N', 'MM3': ['155']},
        'N_164': {'element': 'N', 'MM3': ['164']},
        'N_R': {'element': 'N', 'MM3': ['37']},
        'N_40': {'element': 'N', 'MM3': ['40']},
        'N_143': {'element': 'N', 'MM3': ['143']},
        'N_144': {'element': 'N', 'MM3': ['144']},
        'N_151': {'element': 'N', 'MM3': ['151']},
        'N_2': {'element': 'N', 'MM3': ['9']},
        'N_43': {'element': 'N', 'MM3': ['43']},
        'N_45': {'element': 'N', 'MM3': ['45']},
        'N_46': {'element': 'N', 'MM3': ['46']},
        'N_72': {'element': 'N', 'MM3': ['72']},
        'N_107': {'element': 'N', 'MM3': ['107']},
        'N_108': {'element': 'N', 'MM3': ['108']},
        'N_109': {'element': 'N', 'MM3': ['109']},
        'N_110': {'element': 'N', 'MM3': ['110']},
        'N_111': {'element': 'N', 'MM3': ['111']},
        'N_1': {'element': 'N', 'MM3': ['10']},
        'F_': {'element': 'F', 'MM3': ['11']},
        'CL': {'element': 'Cl', 'MM3': ['12']},
        'BR': {'element': 'Br', 'MM3': ['13']},
        'I_': {'element': 'I', 'MM3': ['14']},
        'S_3+2': {'element': 'S', 'MM3': ['15']},
        'S_16': {'element': 'S', 'MM3': ['16']},
        'S_17': {'element': 'S', 'MM3': ['17']},
        'S_18': {'element': 'S', 'MM3': ['18']},
        'S_104': {'element': 'S', 'MM3': ['104']},
        'S_105': {'element': 'S', 'MM3': ['105']},
        'S_3+4': {'element': 'S', 'MM3': ['154']},
        'S_3+6': {'element': 'S', 'MM3': ['154']},
        'S_R': {'element': 'S', 'MM3': ['42']},
        'S_2': {'element': 'S', 'MM3': ['74']},
        'P_3+3': {'element': 'P', 'MM3': ['25']},
        'P_3+5': {'element': 'P', 'MM3': ['25']},
        'P_60': {'element': 'P', 'MM3': ['60']},
        'P_153': {'element': 'P', 'MM3': ['153']},
        'P_3+Q': {'element': 'P', 'MM3': ['25']},
        'B_2': {'element': 'B', 'MM3': ['26']},
        'B_3': {'element': 'B', 'MM3': ['27']},
        'SI3': {'element': 'Si', 'MM3': ['19']},
        'SN3': {'element': 'Se', 'MM3': ['32']},
        'HE4+4': {'element': 'He', 'MM3': ['51']},
        'NE4+4': {'element': 'Ne', 'MM3': ['52']},
        'AR4+4': {'element': 'Ar', 'MM3': ['53']},
        'KR4+4': {'element': 'Kr', 'MM3': ['54']},
        'XE4+4': {'element': 'Xe', 'MM3': ['55']},
        'LI': {'element': 'Li', 'MM3': ['163']},
        'MG3+2': {'element': 'Mg', 'MM3': ['59']},
        'GE3': {'element': 'Ge', 'MM3': ['31']},
        'PB3': {'element': 'Pb', 'MM3': ['33']},
        'SE3+2': {'element': 'Se', 'MM3': ['34']},
        'TE3+2': {'element': 'Te', 'MM3': ['35']},
        'CA6+2': {'element': 'Ca', 'MM3': ['125']},
        'SR6+2': {'element': 'Sr', 'MM3': ['126']},
        'BA6+2': {'element': 'Ba', 'MM3': ['127']},
        'FE3+2': {'element': 'Fe', 'MM3': ['62']},
        'FE_61': {'element': 'Fe', 'MM3': ['61']},
        'FE6+2': {'element': 'Fe', 'MM3': ['62']},
        'NI4+2': {'element': 'Ni', 'MM3': ['63']},
        'NI_64': {'element': 'Ni', 'MM3': ['64']},
        'CO6+3': {'element': 'Co', 'MM3': ['66']},
        'CO_65': {'element': 'Co', 'MM3': ['65']},
        'LA3+3': {'element': 'La', 'MM3': ['128']},
        'CE6+3': {'element': 'Ce', 'MM3': ['129']},
        'PR6+3': {'element': 'Pr', 'MM3': ['130']},
        'ND6+3': {'element': 'Nd', 'MM3': ['131']},
        'PM6+3': {'element': 'Pm', 'MM3': ['132']},
        'SM6+3': {'element': 'Sm', 'MM3': ['133']},
        'EU6+3': {'element': 'Eu', 'MM3': ['134']},
        'GD6+3': {'element': 'Gd', 'MM3': ['135']},
        'TB6+3': {'element': 'Tb', 'MM3': ['136']},
        'DY6+3': {'element': 'Dy', 'MM3': ['137']},
        'HO6+3': {'element': 'Ho', 'MM3': ['138']},
        'ER6+3': {'element': 'Er', 'MM3': ['139']},
        'TM6+3': {'element': 'Tm', 'MM3': ['140']},
        'YB6+3': {'element': 'Yb', 'MM3': ['141']},
        'LU6+3': {'element': 'Lu', 'MM3': ['142']},
        'BE3+2': {'element': 'Be', 'MM3': ['165']},
        'NA': {'element': 'Na', 'MM3': ['166']},
        'AL3': {'element': 'Al', 'MM3': ['167']},
        'K_': {'element': 'K', 'MM3': ['168']},
        'SC3+3': {'element': 'Sc', 'MM3': ['169']},
        'TI3+4': {'element': 'Ti', 'MM3': ['170']},
        'TI6+4': {'element': 'Ti', 'MM3': ['170']},
        'V_3+5': {'element': 'V', 'MM3': ['171']},
        'CR6+3': {'element': 'Cr', 'MM3': ['172']},
        'MN6+2': {'element': 'Mn', 'MM3': ['173']},
        'CU3+1': {'element': 'Cu', 'MM3': ['174']},
        'ZN3+2': {'element': 'Zn', 'MM3': ['175']},
        'GA3+3': {'element': 'Ga', 'MM3': ['176']},
        'AS3+3': {'element': 'As', 'MM3': ['177']},
        'RB': {'element': 'Rb', 'MM3': ['178']},
        'Y_3+3': {'element': 'Y', 'MM3': ['179']},
        'ZR3+4': {'element': 'Zr', 'MM3': ['180']},
        'NB3+5': {'element': 'Nb', 'MM3': ['181']},
        'MO6+6': {'element': 'Mo', 'MM3': ['182']},
        'MO3+6': {'element': 'Mo', 'MM3': ['182']},
        'TC6+5': {'element': 'Tc', 'MM3': ['183']},
        'RU6+2': {'element': 'Ru', 'MM3': ['184']},
        'RH6+3': {'element': 'Rh', 'MM3': ['185']},
        'PD4+2': {'element': 'Pd', 'MM3': ['186']},
        'AG1+1': {'element': 'Ag', 'MM3': ['187']},
        'CD3+2': {'element': 'Cd', 'MM3': ['188']},
        'IN3+3': {'element': 'In', 'MM3': ['189']},
        'SB3+3': {'element': 'Sb', 'MM3': ['190']},
        'CS': {'element': 'Cs', 'MM3': ['191']},
        'HF3+4': {'element': 'Hf', 'MM3': ['192']},
        'TA3+5': {'element': 'Ta', 'MM3': ['193']},
        'W_6+6': {'element': 'W', 'MM3': ['194']},
        'W_3+4': {'element': 'W', 'MM3': ['194']},
        'W_3+6': {'element': 'W', 'MM3': ['194']},
        'RE6+5': {'element': 'Re', 'MM3': ['195']},
        'RE3+7': {'element': 'Re', 'MM3': ['195']},
        'OS6+6': {'element': 'Os', 'MM3': ['196']},
        'IR6+3': {'element': 'Ir', 'MM3': ['197']},
        'PT4+4': {'element': 'Pt', 'MM3': ['198']},
        'AU4+3': {'element': 'Au', 'MM3': ['199']},
        'HG1+2': {'element': 'Hg', 'MM3': ['200']},
        'TL3+3': {'element': 'Tl', 'MM3': ['201']},
        'BI3+3': {'element': 'Bi', 'MM3': ['202']},
        'PO3+2': {'element': 'Po', 'MM3': ['203']},
        'AT': {'element': 'At', 'MM3': ['204']},
        'RN4+4': {'element': 'Rn', 'MM3': ['205']},
        'FR': {'element': 'Fr', 'MM3': ['206']},
        'RA6+2': {'element': 'Ra', 'MM3': ['207']},
        'AC6+3': {'element': 'Ac', 'MM3': ['208']},
        'TH6+4': {'element': 'Th', 'MM3': ['209']},
        'PA6+4': {'element': 'Pa', 'MM3': ['210']},
        'U_6+4': {'element': 'U', 'MM3': ['211']},
        'NP6+4': {'element': 'Np', 'MM3': ['212']},
        'PU6+4': {'element': 'Pu', 'MM3': ['213']},
        'AM6+4': {'element': 'Am', 'MM3': ['214']},
        'CM6+3': {'element': 'Cm', 'MM3': ['215']},
        'BK6+3': {'element': 'Bk', 'MM3': ['216']},
        'CF6+3': {'element': 'Cf', 'MM3': ['217']},
        'ES6+3': {'element': 'Es', 'MM3': ['218']},
        'FM6+3': {'element': 'Fm', 'MM3': ['219']},
        'MD6+3': {'element': 'Md', 'MM3': ['220']},
        'NO6+3': {'element': 'No', 'MM3': ['221']},
        'LW6+3': {'element': 'Lw', 'MM3': ['222']}
    },
    'MM3': {
        '1': {'element': 'C'},
        '2': {'element': 'C'},
        '3': {'element': 'C'},
        '4': {'element': 'C'},
        '5': {'element': 'H'},
        '6': {'element': 'O'},
        '7': {'element': 'O'},
        '8': {'element': 'N'},
        '9': {'element': 'N'},
        '10': {'element': 'N'},
        '11': {'element': 'F'},
        '12': {'element': 'Cl'},
        '13': {'element': 'Br'},
        '14': {'element': 'I'},
        '15': {'element': 'S'},
        '16': {'element': 'S'},
        '17': {'element': 'S'},
        '18': {'element': 'S'},
        '19': {'element': 'Si'},
        '20': {'element': ''},
        '21': {'element': 'H'},
        '22': {'element': 'C'},
        '23': {'element': 'H'},
        '24': {'element': 'H'},
        '25': {'element': 'P'},
        '26': {'element': 'B'},
        '27': {'element': 'B'},
        '28': {'element': 'H'},
        '29': {'element': 'C'},
        '30': {'element': 'C'},
        '31': {'element': 'Ge'},
        '32': {'element': 'Sn'},
        '33': {'element': 'Pb'},
        '34': {'element': 'Se'},
        '35': {'element': 'Te'},
        '36': {'element': 'C'},
        '37': {'element': 'N'},
        '38': {'element': 'C'},
        '39': {'element': 'N'},
        '40': {'element': 'N'},
        '41': {'element': 'O'},
        '42': {'element': 'S'},
        '43': {'element': 'N'},
        '44': {'element': 'H'},
        '45': {'element': 'N'},
        '46': {'element': 'N'},
        '47': {'element': 'O'},
        '48': {'element': 'H'},
        '49': {'element': 'O'},
        '50': {'element': 'C'},
        '51': {'element': 'He'},
        '52': {'element': 'Ne'},
        '53': {'element': 'Ar'},
        '54': {'element': 'Kr'},
        '55': {'element': 'Xe'},
        '56': {'element': 'C'},
        '57': {'element': 'C'},
        '58': {'element': 'C'},
        '59': {'element': 'Mg'},
        '60': {'element': 'P'},
        '61': {'element': 'Fe'},
        '62': {'element': 'Fe'},
        '63': {'element': 'Ni'},
        '64': {'element': 'Ni'},
        '65': {'element': 'Co'},
        '66': {'element': 'Co'},
        '67': {'element': 'C'},
        '68': {'element': 'C'},
        '69': {'element': 'O'},
        '70': {'element': 'O'},
        '71': {'element': 'C'},
        '72': {'element': 'N'},
        '73': {'element': 'H'},
        '74': {'element': 'S'},
        '75': {'element': 'O'},
        '76': {'element': 'O'},
        '77': {'element': 'O'},
        '78': {'element': 'O'},
        '79': {'element': 'O'},
        '80': {'element': 'O'},
        '81': {'element': 'O'},
        '82': {'element': 'O'},
        '83': {'element': 'O'},
        '84': {'element': 'O'},
        '85': {'element': 'O'},
        '86': {'element': 'O'},
        '87': {'element': 'O'},
        '88': {'element': 'O'},
        '89': {'element': 'O'},
        '90': {'element': 'O'},
        '91': {'element': 'O'},
        '92': {'element': 'O'},
        '93': {'element': 'O'},
        '94': {'element': 'O'},
        '95': {'element': 'O'},
        '96': {'element': 'O'},
        '97': {'element': 'O'},
        '98': {'element': 'O'},
        '99': {'element': 'O'},
        '100': {'element': 'O'},
        '101': {'element': 'O'},
        '102': {'element': 'O'},
        '103': {'element': 'O'},
        '104': {'element': 'S'},
        '105': {'element': 'S'},
        '106': {'element': 'C'},
        '107': {'element': 'N'},
        '108': {'element': 'N'},
        '109': {'element': 'N'},
        '110': {'element': 'N'},
        '111': {'element': 'N'},
        '112': {'element': ''},
        '113': {'element': 'C'},
        '114': {'element': 'C'},
        '115': {'element': 'O'},
        '116': {'element': 'O'},
        '117': {'element': 'O'},
        '118': {'element': 'O'},
        '119': {'element': 'O'},
        '120': {'element': 'O'},
        '121': {'element': 'O'},
        '122': {'element': ''},
        '123': {'element': ''},
        '124': {'element': 'H'},
        '125': {'element': 'Ca'},
        '126': {'element': 'Sr'},
        '127': {'element': 'Ba'},
        '128': {'element': 'La'},
        '129': {'element': 'Ce'},
        '130': {'element': 'Pr'},
        '131': {'element': 'Nd'},
        '132': {'element': 'Pm'},
        '133': {'element': 'Sm'},
        '134': {'element': 'Eu'},
        '135': {'element': 'Gd'},
        '136': {'element': 'Tb'},
        '137': {'element': 'Dy'},
        '138': {'element': 'Ho'},
        '139': {'element': 'Er'},
        '140': {'element': 'Tm'},
        '141': {'element': 'Yb'},
        '142': {'element': 'Lu'},
        '143': {'element': 'N'},
        '144': {'element': 'N'},
        '145': {'element': 'O'},
        '146': {'element': 'N'},
        '147': {'element': ''},
        '148': {'element': 'O'},
        '149': {'element': 'O'},
        '150': {'element': 'N'},
        '151': {'element': 'N'},
        '152': {'element': ''},
        '153': {'element': 'P'},
        '154': {'element': 'S'},
        '155': {'element': 'N'},
        '156': {'element': ''},
        '157': {'element': ''},
        '158': {'element': ''},
        '159': {'element': 'O'},
        '160': {'element': 'C'},
        '161': {'element': 'C'},
        '162': {'element': 'C'},
        '163': {'element': 'Li'},
        '164': {'element': 'N'}
    },
    'MM3PRO': {
        '1': {'element': 'C'},
        '2': {'element': 'C'},
        '3': {'element': 'C'},
        '4': {'element': 'C'},
        '5': {'element': 'C'},
        '6': {'element': 'C'},
        '7': {'element': 'C'},
        '8': {'element': 'N'},
        '9': {'element': 'N'},
        '10': {'element': 'N'},
        '11': {'element': 'N'},
        '12': {'element': 'N'},
        '13': {'element': 'O'},
        '14': {'element': 'O'},
        '15': {'element': 'O'},
        '16': {'element': 'O'},
        '17': {'element': 'O'},
        '18': {'element': 'S'},
        '19': {'element': 'H'},
        '20': {'element': 'H'},
        '21': {'element': 'H'},
        '22': {'element': 'H'},
        '23': {'element': 'H'},
        '24': {'element': 'H'},
        '25': {'element': 'H'},
        '26': {'element': 'H'},
        '27': {'element': 'H'}
    }
}

"""
#OLD STUFF THAT MAY BE USEFUL IN FUTURE

GAFF_DESC = {
    'c': 'Sp2 C carbonyl group',
    'c1': 'Sp C',
    'c2': 'Sp2 C', 
    'c3': 'Sp3 C',
    'ca': 'Sp2 C in pure aromatic systems',
    'cp': 'Head Sp2 C that connect two rings in biphenyl sys.',
    'cq': 'Head Sp2 C that connect two rings in biphenyl sys. identical to cp',
    'cc': 'Sp2 carbons in non-pure aromatic systems',
    'cd': 'Sp2 carbons in non-pure aromatic systems, identical to cc',
    'ce': 'Inner Sp2 carbons in conjugated systems',
    'cf': 'Inner Sp2 carbons in conjugated systems, identical to ce',
    'cg': 'Inner Sp carbons in conjugated systems',
    'ch': 'Inner Sp carbons in conjugated systems, identical to cg',
    'cx': 'Sp3 carbons in triangle systems',
    'cy': 'Sp3 carbons in square systems',
    'cu': 'Sp2 carbons in triangle systems',
    'cv': 'Sp2 carbons in square systems',
    'cz': 'Sp2 carbon in guanidine group',
    'h1': 'H bonded to aliphatic carbon with 1 electrwd. group',
    'h2': 'H bonded to aliphatic carbon with 2 electrwd. group',
    'h3': 'H bonded to aliphatic carbon with 3 electrwd. group',
    'h4': 'H bonded to non-sp3 carbon with 1 electrwd. group',
    'h5': 'H bonded to non-sp3 carbon with 2 electrwd. group',
    'ha': 'H bonded to aromatic carbon',
    'hc': 'H bonded to aliphatic carbon without electrwd. group',
    'hn': 'H bonded to nitrogen atoms',
    'ho': 'Hydroxyl group',
    'hp': 'H bonded to phosphate',
    'hs': 'Hydrogen bonded to sulphur',
    'hw': 'Hydrogen in water',
    'hx': 'H bonded to C next to positively charged group',
    'f':  'Fluorine',
    'cl': 'Chlorine',
    'br': 'Bromine',
    'i':  'Iodine',
    'n':  'Sp2 nitrogen in amide groups',
    'n1': 'Sp N',
    'n2': 'Aliphatic Sp2 N with two connected atoms',
    'n3': 'Sp3 N with three connected atoms',
    'n4': 'Sp3 N with four connected atoms',
    'na': 'Sp2 N with three connected atoms',
    'nb': 'Sp2 N in pure aromatic systems',
    'nc': 'Sp2 N in non-pure aromatic systems',
    'nd': 'Sp2 N in non-pure aromatic systems',
    'ne': 'Inner Sp2 N in conjugated systems',
    'nf': 'Inner Sp2 N in conjugated systems',
    'nh': 'Amine N connected one or more aromatic rings',
    'no': 'Nitro N',
    'o': 'Oxygen with one connected atom',
    'oh': 'Oxygen in hydroxyl group',
    'os': 'Ether and ester oxygen',
    'ow': 'Oxygen in water',
    'p2': 'Phosphate with two connected atoms',
    'p3': 'Phosphate with three connected atoms, such as PH3',
    'p4': 'Phosphate with three connected atoms, such as O=P(CH3)2',
    'p5': 'Phosphate with four connected atoms, such as O=P(OH)3',
    'pb': 'Sp2 P in pure aromatic systems',
    'pc': 'Sp2 P in non-pure aromatic systems',
    'pd': 'Sp2 P in non-pure aromatic systems, identical to pc',
    'pe': 'Inner Sp2 P in conjugated systems',
    'pf': 'Inner Sp2 P in conjugated systems, identical to pe',
    'px': 'Special p4 in conjugated systems',
    'py': 'Special p5 in conjugated systems',
    's': 'S with one connected atom',
    's2': 'S with two connected atom, involved at least one double bond',
    's4': 'S with three connected atoms', 
    's6': 'S with four connected atoms',
    'sh': 'Sp3 S connected with hydrogen',
    'ss': 'Sp3 S in thio-ester and thio-ether',
    'sx': 'Special s4 in conjugated systems',
    'sy': 'Special s6 in conjugated systems'
}

MM3_FROM_ELEMENT = {
    'Ac': ['208'],
    'Ag': ['187'],
    'Al': ['167'],
    'Am': ['214'],
    'Ar': ['53'],
    'As': ['177'],
    'At': ['204'],
    'Au': ['199'],
    'B': ['26', '27'],
    'Ba': ['127'],
    'Be': ['165'],
    'Bi': ['202'],
    'Bk': ['216'],
    'Br': ['13'],
    'C': ['1', '2', '3', '4', '22', '29', '30', '38', '50', '56', '57', '58', '67', '68', '71', '106', '113', '114', '160', '161', '162'],
    'Ca': ['125'],
    'Cd': ['188'],
    'Ce': ['129'],
    'Cf': ['217'],
    'Cl': ['12'],
    'Cm': ['215'],
    'Co': ['65', '66'],
    'Cr': ['172'],
    'Cs': ['191'],
    'Cu': ['174'],
    'D': ['36'],
    'Dy': ['137'],
    'Er': ['139'],
    'Es': ['218'],
    'Eu': ['134'],
    'F': ['11'],
    'Fe': ['61', '62'],
    'Fm': ['219'],
    'Fr': ['206'],
    'Ga': ['176'],
    'Gd': ['135'],
    'Ge': ['31'],
    'H': ['5', '21', '23', '24', '28', '44', '48', '73', '124'],
    'He': ['51'],
    'Hf': ['192'],
    'Hg': ['200'],
    'Ho': ['138'],
    'I': ['14'],
    'In': ['189'],
    'Ir': ['197'],
    'K': ['168'],
    'Kr': ['54'],
    'La': ['128'],
    'Li': ['163'],
    'Lu': ['142'],
    'Lw': ['222'],
    'Md': ['220'],
    'Mg': ['59'],
    'Mn': ['173'],
    'Mo': ['182'],
    'N': ['8', '9', '10', '37', '39', '40', '43', '45', '46', '72', '107', '108', '109', '110', '111', '143', '144', '146', '150', '151', '155', '164'],
    'Na': ['166'],
    'Nb': ['181'],
    'Nd': ['131'],
    'Ne': ['52'],
    'Ni': ['63', '64'],
    'No': ['221'],
    'Np': ['212'],
    'O': ['6', '7', '41', '47', '49', '69', '70', '75', '76', '77', '78', '79', '80', '81', '82', '83', '84', '85', '86', '87', '88', '89', '90', '91', '92', '93', '94', '95', '96', '97', '98', '99', '100', '101', '102', '103', '115', '116', '117', '118', '119', '120', '121', '145', '148', '149', '159'],
    'Os': ['196'],
    'P': ['25', '60', '153'],
    'Pa': ['210'],
    'Pb': ['33'],
    'Pd': ['186'],
    'Pm': ['132'],
    'Po': ['203'],
    'Pr': ['130'],
    'Pt': ['198'],
    'Pu': ['213'],
    'Ra': ['207'],
    'Rb': ['178'],
    'Re': ['195'],
    'Rh': ['185'],
    'Rn': ['205'],
    'Ru': ['184'],
    'S': ['15', '16', '17', '18', '42', '74', '104', '105', '154'],
    'Sb': ['190'],
    'Sc': ['169'],
    'Se': ['34'],
    'Si': ['19'],
    'Sm': ['133'],
    'Sn': ['32'],
    'Sr': ['126'],
    'Ta': ['193'],
    'Tb': ['136'],
    'Tc': ['183'],
    'Te': ['35'],
    'Th': ['209'],
    'Ti': ['170'],
    'Tl': ['201'],
    'Tm': ['140'],
    'U': ['211'],
    'V': ['171'],
    'W': ['194'],
    'Xe': ['55'],
    'Y': ['179'],
    'Yb': ['141'],
    'Zn': ['175'],
    'Zr': ['180']
}
"""